name: Build and test
on: push

env:  
  VERSION: 0.1.${{github.run_number}}
  CANISTER_URL: cloud.canister.io:5000
  CR_URL: c8n.io
  REPO: portfolio

jobs:
  build_and_test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: true
    #  matrix:
    #    machines: [1,2,3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn install; yarn build

      - name: Run Jest
        run: yarn start & yarn test:unit

      - name: Run Cypress
        run: yarn start & yarn test:ui:run
  
      - name: Build Docker image
        run: |
          echo build the image using the Dockerfile in devops folder
          docker image build -t $REPO:0 -f devops/Dockerfile .    
          echo ---

          echo Canister Login and Push
          echo docker login on Canister          
          echo ${{secrets.CANISTER_PWD}}| docker login -u ${{secrets.CANISTER_USERID}} $CANISTER_URL --password-stdin 
          echo re-tag and push the image $REPO:$VERSION               
          docker image tag $REPO:0 $CANISTER_URL/${{secrets.CANISTER_USERID}}/$REPO:$VERSION   
          docker image push $CANISTER_URL/${{secrets.CANISTER_USERID}}/$REPO:$VERSION 
          echo re-tag and push the image $REPO:latest   
          docker image tag $CANISTER_URL/${{secrets.CANISTER_USERID}}/$REPO:$VERSION $CANISTER_URL/${{secrets.CANISTER_USERID}}/$REPO:latest   
          docker image push $CANISTER_URL/${{secrets.CANISTER_USERID}}/$REPO:latest 
          echo ---

          echo Container Registry Login and Push
          echo ${{secrets.CR_PWD}}| docker login -u ${{secrets.CR_USERID}} $CR_URL --password-stdin     
          echo re-tag and push the image $REPO:0 
          docker image tag $REPO:$VERSION $CR_URL/${{secrets.CR_USERID}}/$REPO:$VERSION
          docker image push $CR_URL/${{secrets.CR_USERID}}/$REPO:$VERSION 
          echo ---

