name: Build and test
on: 
  #push:
  pull_request:
    #types: [opened, synchronize, reopened, labeled]  
    types: [labeled]    

env:  
  VERSION: 0.1.${{github.run_number}}
  CR_URL: c8n.io
  REPO: portfolio

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: true
    #  matrix:
    #    machines: [1,2,3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn install; yarn build
      - name: Upload Build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build_artifact
          path: ./.next/

  tests_jest:
    name: Run Tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v2
      - name: Download Build artifact
        uses: actions/download-artifact@v3
        with:
          name: build_artifact
      - name: Run Jest
        run: yarn start & yarn test:unit
      - name: Run Cypress
        run: yarn start & yarn test:ui:run
  
  #    - name: Build Docker image
  #      run: |
  #        echo build the image using the Dockerfile in devops folder
  #        docker image build -t $REPO:0 -f devops/Dockerfile.2 .    
  #        echo -----
  #        echo ### Container Registry Login and Push ###
  #        echo ${{secrets.CR_PWD}}| docker login -u ${{secrets.CR_USERID}} $CR_URL --password-stdin
  #        echo re-tag and push the images
  #        docker image tag $REPO:0 $CR_URL/${{secrets.CR_USERID}}/$REPO:$VERSION
  #        docker image tag $REPO:0 $CR_URL/${{secrets.CR_USERID}}/$REPO:latest
  #        docker image push $CR_URL/${{secrets.CR_USERID}}/$REPO:$VERSION           
  #        docker image push $CR_URL/${{secrets.CR_USERID}}/$REPO:latest 
  #        echo -----

  build_docker_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [build, tests_jest]
    steps:
      # Do we need checkout? https://stackoverflow.com/questions/71668199/github-action-job-can-continue-from-the-state-the-previous-job-left-without-a
      #- name: Checkout
      #  uses: actions/checkout@v2
      - name: Build Docker image
        if: github.event.action == 'labeled' && github.event.label.name == 'docker:image'
        run: |
          echo build the image using the Dockerfile in devops folder
          docker image build -t $REPO:0 -f devops/Dockerfile.2 .    
          echo -----
          echo ### Container Registry Login and Push ###
          echo ${{secrets.CR_PWD}}| docker login -u ${{secrets.CR_USERID}} $CR_URL --password-stdin
          echo re-tag and push the images
          docker image tag $REPO:0 $CR_URL/${{secrets.CR_USERID}}/$REPO:$VERSION
          docker image tag $REPO:0 $CR_URL/${{secrets.CR_USERID}}/$REPO:latest
          docker image push $CR_URL/${{secrets.CR_USERID}}/$REPO:$VERSION           
          docker image push $CR_URL/${{secrets.CR_USERID}}/$REPO:latest 
          echo -----

