name: Build and test
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: true
    #  matrix:
    #    machines: [1,2,3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          #start: yarn dev
          #start: yarn install; yarn build; yarn start
          record: true
          command: yarn install; yarn build; yarn start
        env:         
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}} # key od project created in cypress.io
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided