# build the soluton and execute tests
# https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Build and Test (reusable)
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  info:
    name: Info for ${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - name: action
        run: |
          echo "Info:"
          echo github.event.action - ${{ github.event.action }}
          echo github.head_ref     - ${{ github.head_ref }}
