name: Build and test
on: push

jobs:
  build_and_test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: true
    #  matrix:
    #    machines: [1,2,3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn install; yarn build

      - name: Run Jest
        run: yarn start & yarn test:unit

      - name: Run Cypress
        run: yarn start & yarn test:ui:run
  
  create_docker_image:
    name: "Create Docker image"
    runs-on: ubuntu-latest

    steps:
      - name: build
        run: echo "not implemented"