name: Build and test
on:
  push:
    branches: [feature]

env:
  VERSION: 0.1.${{github.run_number}}
  IMAGE: portfolio-web

jobs:
  info:
    name: Info for ${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - name: action
        run: |
          echo github.event.action - ${{ github.event.action }}
          echo github.head_ref     - ${{ github.head_ref }}
