name: Cypress tests
on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress runs
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          record: true
        env:         
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}} # key od project created in cypress.io
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided