name: Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure environment
        run: >
          ls -l ./devops
          echo change permissions
          chmod +x ./devops/*
          ls -l ./devops

      - name: execute script
        run: ./devops/test.sh