name: Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure environment
        run: |
          chmod +x ./devops/test.sh
          ./devops/test.sh

      - name: Check
        run: |
          cat .env
          