name: Build Feature Preview

on:
  push:
    branches: feature/**

jobs:
  call-build-and-test-workflow:
    name: build and test
    uses: ./.github/workflows/build_and_test.yml

  call-create-image-workflow:
    name: create Docker image
    needs: call-build-and-test-workflow
    uses: ./.github/workflows/create-image.yml
    with:
      version_postfix: "-preview"
    secrets: inherit
