name: Build Preview
on:
  push:
    branches: [feature]

env:
  VERSION: 0.1.${{github.run_number}}
  IMAGE: portfolio-web

jobs:
  call-build-and-test-workflow:
    uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    with:
      config-path: .github/build and test.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
