name: Build Feature Preview

on:
  push:
    branches: feature/**

env:
  IMAGE: portfolio-web
  VERSION: 0.1.${{github.run_number}}-preview

jobs:
  call-build-and-test-workflow:
    name: build and test
    #uses: alex-piccione/portfolio-web-UI/.github/workflows/build_and_test.yml@main
    uses: ./.github/workflows/build_and_test.yml
    #with:
    #  version: $VERSION
    #  image: $IMAGE
    #  config-path: .github/workflows/common/build_and_test.yml
    #secrets:
    #  envPAT: ${{ secrets.envPAT }}

  call-create-image-workflow:
    name: create Docker image
    needs: call-build-and-test-workflow
    uses: ./.github/workflows/create-image.yml
    with:
      image: $IMAGE
      version: $VERSION
    secrets: inherit
