name: Build Feature Preview

on:
  push:
    branches: feature/**

env:
  VERSION: 0.1.${{github.run_number}}-preview
  IMAGE: portfolio-web

jobs:
  call-build-and-test-workflow:
    #uses: alex-piccione/portfolio-web-UI/.github/workflows/build_and_test.yml@main
    uses: ./.github/workflows/build_and_test.yml
    #with:
    #  config-path: .github/workflows/common/build_and_test.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
