name: Build and Test
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

env:
  IMAGE: ${{ inputs.image }}

jobs:dd env
  print_variables:
    name: "Print variables"
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutprint
        run: echo I\'m a test for the image ${{ inputs.image }}
