name: Build and Test
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  print_variables:
    name: "Print variables"
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutprint
        run: echo I'm a test for the image ${{ inputs.image }}
