name: Deploy on VPS

on: 
  push:
    branches: [main]

env:  
  HOST: ${{ secrets.host_ip }}
  USER: ${{ secrets.host_user }}
  PRIVATE_SSH_KEY: ${{ secrets.host_ssh_private_key }}

jobs: 
  ssh_test:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        run: |
          echo SSH connection 
          echo "$PRIVATE_SSH_KEY" >> key 
          ssh -i key $USER@$HOST ls /tmp/doc
          rm key

