name: Deploy on VPS

on: 
  push:
    branches: [main]

env:  
  HOST: ${{ secrets.host_ip }}
  HOST_ID: ${{ secrets.host_id }}
  KNOWN_HOST: ${{ secrets.known_host }}
  USER: ${{ secrets.host_user }}
  SSH_PRIVATE_KEY: ${{ secrets.host_ssh_private_key }}

jobs: 
  ssh_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "$SSH_PRIVATE_KEY"          
          
      - name: ssh
        run: |
          echo SSH connection 
          echo add server "key" to ~/.ssh/authorized_keys
          #touch ~/.ssh/authorized_keys
          mkdir ~/.ssh
          #echo "$HOST_ID" >> ~/.ssh/authorized_keys
          echo "$KNOWN_HOST" >> ~/.ssh/known_host
          echo "$SSH_PRIVATE_KEY" >> key 
          ssh -i key $USER@$HOST ls /tmp/doc
          rm key

